server:
  port: 9000
  #eureka server 的配置
  #register-with-eureka:表示该eureka节点不能注册服务
  #fetch-registry:表示该eureka节点不能发现（订阅）服务
  #instance.secure-port-enabled:安全保护机制（端口）关闭
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
    register-with-eureka: false
    fetch-registry: false
    instance:
      secure-port-enabled: false

